version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: MOHANraj
      MYSQL_DATABASE: my_database
    ports:
      - "3307:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: MOHANraj
      MYSQL_HOST: db
      MYSQL_PORT: 3306

  liquibase:
    build:
      context: .
      dockerfile: Dockerfile-liquibase
    depends_on:
      - db
    entrypoint: ["liquibase", "--changeLogFile=db.changelog.xml", "update"]
